apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: K0sWorkerConfigTemplate
metadata:
  name: {{ include "k0sworkerconfigtemplate.name" . }}
  namespace: {{ .Values.cluster.namespace | default .Release.Namespace | trunc 63 }}
spec:
  template:
    spec:
      {{- if .Values.k0s.downloadURL }}
      downloadURL: "{{ .Values.k0s.downloadURL }}"
      {{- end }}
      version: {{ .Values.k0s.version }}
      useSystemHostname: {{ .Values.worker.useSystemHostname | default false }}
      {{- if .Values.worker.preInstalledK0s }}
      preInstalledK0s: {{ .Values.worker.preInstalledK0s }}
      {{- end }}
      {{- if .Values.k0s.cloudProvider.enabled }}
      args:
        - --enable-cloud-provider
        - --kubelet-extra-args="--cloud-provider=external"
      {{- end }}
      {{- if .Values.worker.files }}
      files:
        {{- toYaml .Values.worker.files | nindent 8 }}
      {{- end }}
      {{- with .Values.worker.preStartCommands }}
      preStartCommands:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.worker.postStartCommands }}
      postStartCommands:
        {{- toYaml . | nindent 8 }}
      {{- end }}
