apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kcm-manager-role-hetznerclusters
rules:
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - hetznerclusters
  - hetznerclustertemplates
  - hetznerbaremetalhosts
  - hetznerbaremetalmachines
  - hetznerbaremetalmachinetemplates
  - hetznerbaremetalremediations
  - hetznerbaremetalremediationtemplates
  verbs:
  - get
  - list
  - patch
  - watch
