---
apiVersion: k0rdent.mirantis.com/v1beta1
kind: ProviderInterface
metadata:
  name: cluster-api-provider-hetzner
  annotations:
    helm.sh/resource-policy: keep
spec:
  clusterGVKs:
    - group: infrastructure.cluster.x-k8s.io
      version: v1alpha1
      kind: HetznerCluster
  clusterIdentityKinds:
    - Secret
  description: "Hetzner infrastructure provider for Cluster API"
