apiVersion: operator.cluster.x-k8s.io/v1alpha2
kind: InfrastructureProvider
metadata:
  name: hetzner
  namespace: {{ .Release.Namespace }}
spec:
  version: {{ printf "v%s" .Chart.AppVersion | quote }}
  {{- if .Values.config.secret.name }}
  configSecret:
    name: {{ .Values.config.secret.name }}
    namespace: {{ .Release.Namespace }}
  {{- end }}
  {{- if .Values.manager }}
  manager: {{ toYaml .Values.manager | nindent 4 }}
  {{- end }}
