{{- if .Values.providerTemplate.enabled }}
---
apiVersion: k0rdent.mirantis.com/v1beta1
kind: ProviderTemplate
metadata:
  name: cluster-api-provider-nutanix-hcp
  annotations:
    helm.sh/resource-policy: keep
spec:
  providers:
    - name: nutanix
      type: Infrastructure
      version: {{ .Values.capx.version | quote }}
      {{- if .Values.capx.namespace }}
      namespace: {{ .Values.capx.namespace | quote }}
      {{- end }}
  capiOperator:
    # ToDo: make this field configurable from Helm values
    enabled: true
  helm:
    chartSpec:
      chart: cluster-api-provider-nutanix
      version: {{ .Values.capx.version | quote }}
      interval: 10m0s
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: kcm-templates
{{- end }}
