{{- if .Values.providerTemplate.enabled }}
---
apiVersion: k0rdent.mirantis.com/v1beta1
kind: ProviderTemplate
metadata:
  name: cluster-api-provider-nutanix-hcp
  annotations:
    helm.sh/resource-policy: keep
spec:
  providers:
    - "nutanix"
  helm:
    chartSpec:
      chart: cluster-api-provider-nutanix
      version: {{ .Chart.Version | quote }}
      interval: 10m0s
      sourceRef:
        kind: HelmRepository
        name: oot-repo
{{- end }}
