---
apiVersion: k0rdent.mirantis.com/v1beta1
kind: ClusterTemplate
metadata:
  name: nutanix-k0s-standalone-{{ .Values.chartVersion | replace "." "-" }}
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  helm:
    chartSpec:
      chart: nutanix-capx-standalone
      version: {{ .Values.chartVersion | quote }}
      interval: 10m0s
      sourceRef:
        kind: HelmRepository
        name: oot-repo
