config: # @schema description: Configuration settings; type: object
  secret:
    create: false # @schema description: Whether to create a new secret; type: boolean
    name: "" # @schema description: Name for objects to use; type: string
    data: {} # @schema description: Secret data; type: object; additionalProperties: true

manager: {}
