{{- if .Values.clusterTemplates.hcp.enabled }}
---
apiVersion: k0rdent.mirantis.com/v1beta1
kind: ClusterTemplate
metadata:
  name: nutanix-k0s-hcp-{{ .Values.clusterTemplates.hcp.version | replace "." "-" }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  helm:
    chartSpec:
      chart: nutanix-capx
      version: {{ .Values.clusterTemplates.hcp.version | quote }}
      interval: 10m0s
      sourceRef:
        kind: HelmRepository
        name: oot-repo
      valuesFrom:
        - kind: ConfigMap
          name: nutanix-hcp-cluster-config
          valuesKey: values.yaml
          optional: true
{{- end }}

{{- if .Values.clusterTemplates.standalone.enabled }}
---
apiVersion: k0rdent.mirantis.com/v1beta1
kind: ClusterTemplate
metadata:
  name: nutanix-k0s-standalone-{{ .Values.clusterTemplates.standalone.version | replace "." "-" }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  helm:
    chartSpec:
      chart: nutanix-capx
      version: {{ .Values.clusterTemplates.standalone.version | quote }}
      interval: 10m0s
      sourceRef:
        kind: HelmRepository
        name: oot-repo
      valuesFrom:
        - kind: ConfigMap
          name: nutanix-standalone-cluster-config
          valuesKey: values.yaml
          optional: true
{{- end }}
