{{- if gt (int .Values.workersNumber) 0 }}
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: {{ include "machinedeployment.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  clusterName: {{ include "cluster.name" . }}
  replicas: {{ .Values.workersNumber }}
  selector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: {{ include "cluster.name" . }}
  template:
    metadata:
      labels:
        cluster.x-k8s.io/cluster-name: {{ include "cluster.name" . }}
        {{- if .Values.worker.machineTemplate }}
        {{- with .Values.worker.machineTemplate.metadata.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- end }}
      {{- if .Values.worker.machineTemplate }}
      {{- with .Values.worker.machineTemplate.metadata.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
    spec:
      version: {{ (split "+" .Values.k0s.version)._0 }}
      clusterName: {{ include "cluster.name" . }}
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: K0sWorkerConfigTemplate
          name: {{ include "k0sworkerconfigtemplate.name" . }}
          namespace: {{ .Release.Namespace }}
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: RemoteMachineTemplate
        name: {{ include "remotemachinetemplate.worker.name" . }}
        namespace: {{ .Release.Namespace }}
{{- end }}
