apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kccm-{{ .Values.cluster.namespace | default .Release.Namespace | trunc 63 }}-{{ .Release.Name }}
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get