apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kccm-{{ .Values.cluster.namespace | default .Release.Namespace | trunc 63 }}-{{ .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kccm-{{ .Values.cluster.namespace | default .Release.Namespace | trunc 63 }}-{{ .Release.Name }}
subjects:
- kind: ServiceAccount
  name: cloud-controller-manager-{{ .Release.Name }}
  namespace: {{ .Values.cluster.namespace | default .Release.Namespace | trunc 63 }}