apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kccm-{{ .Values.cluster.namespace | default .Release.Namespace | trunc 63 }}-{{ .Release.Name }}
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
- kind: ServiceAccount
  name: cloud-controller-manager-{{ .Release.Name }}
  namespace: {{ .Values.cluster.namespace | default .Release.Namespace | trunc 63 }}
