# @schema title: KubeVirt Cloud Controller Manager Configuration
# @schema description: Configuration for KubeVirt Cloud Controller Manager deployment

cloudControllerManager:
  replicas: 1
  repo: quay.io/kubevirt
  name: kubevirt-cloud-controller-manager
  tag: main
  topologySpreadConstraints:
    - labelSelector:
        matchLabels:
          k8s-app: kubevirt-cloud-controller-manager-{{ .Release.Name }}
      matchLabelKeys:
        - pod-template-hash
      topologyKey: topology.kubernetes.io/zone
      maxSkew: 1
      whenUnsatisfiable: ScheduleAnyway
