---
apiVersion: k0rdent.mirantis.com/v1beta1
kind: ClusterDeployment
metadata:
  name: nutanix-hcp-smoke-test
  namespace: kcm-system
spec:
  template: nutanix-k0s-hcp-0-1-0  # Matches ClusterTemplate name from provider pack
  # credential: nutanix-cluster-identity-cred  # Only if using per-cluster credentials
  config:
    # Replace these with your actual values
    nutanix:
      prismCentral:
        address: "CHANGE_ME_PC_IP"  # e.g., "10.1.1.100"
        port: 9440
        insecure: false
        # usePerClusterCredential: true  # Uncomment if using per-cluster creds
        # credentialSecretName: "nutanix-cluster-creds"
      
      controlPlaneEndpoint:
        host: "CHANGE_ME_VIP_IP"  # e.g., "10.1.1.200" - OUTSIDE DHCP range!
        port: 6443
    
    machineDefaults:
      image:
        type: name
        name: "CHANGE_ME_IMAGE_NAME"  # e.g., "ubuntu-22.04-k0s"
      cluster:
        type: name
        name: "CHANGE_ME_PE_CLUSTER"  # e.g., "PE-Cluster-01"
      subnets:
        - type: name
          name: "CHANGE_ME_SUBNET"  # e.g., "VM-Network"
      bootType: legacy
      vcpusPerSocket: 1
      vcpuSockets: 2
      memorySize: "4Gi"
      systemDiskSize: "40Gi"
    
    worker:
      vcpuSockets: 2
      memorySize: "4Gi"
      systemDiskSize: "40Gi"
    
    k0s:
      version: "v1.29.2+k0s.0"
      worker:
        labels:
          node-role.kubernetes.io/worker: ""
    
    clusterNetwork:
      pods:
        cidrBlocks: ["10.243.0.0/16"]
      services:
        cidrBlocks: ["10.95.0.0/16"]
    
    # Scaling
    workersNumber: 2
