{{- if .Values.providerTemplate.enabled }}
---
apiVersion: operator.cluster.x-k8s.io/v1alpha2
kind: InfrastructureProvider
metadata:
  name: nutanix
  namespace: {{ .Values.capx.namespace | default "kcm-system" }}
spec:
  version: {{ .Values.capx.version | quote }}
  {{- if .Values.capx.configSecret }}
  configSecret:
    name: {{ .Values.capx.configSecret.name | default "nutanix-creds" }}
    namespace: {{ .Values.capx.configSecret.namespace | default "kcm-system" }}
  {{- end }}
  {{- if .Values.capx.manager }}
  manager: {{ toYaml .Values.capx.manager | nindent 4 }}
  {{- end }}
{{- end }}
