apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kccm-{{ .Release.Name }}
  namespace: {{ .Release.Namespace | trunc 63 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kccm-{{ .Release.Name }}
subjects:
- kind: ServiceAccount
  name: kccm-{{ .Release.Name }}