apiVersion: v1
data:
  cloud-config: |
    {{- if .Values.cloudConfig.kubeconfig }}
    kubeconfig: {{ .Values.cloudConfig.kubeconfig }}
    {{- end }}
    instancesV2:
      enabled: true
      zoneAndRegionEnabled: true
    loadBalancer:
      enabled: {{ .Values.cloudConfig.loadBalancer.enabled }}
      creationPollInterval: 5
      creationPollTimeout: 60
    namespace: {{ .Release.Namespace | trunc 63 }}
kind: ConfigMap
metadata:
  name: cloud-config-{{ .Release.Name }}
  namespace: {{ .Release.Namespace | trunc 63 }}
