# Cluster parameters
controlPlaneNumber: 1 # @schema description: The number of control plane nodes; type: integer; minimum: 1; maximum: 5
workersNumber: 1 # @schema description: The number of worker nodes; type: integer; minimum: 0

clusterIdentity: # @schema description: The Service Account credentials secret reference, auto-populated; type: object
  name: "" # @schema description: The Service Account credentials secret name, auto-populated; type: string

clusterNetwork: # @schema description: The cluster network configuration; type: object
  apiServerHost: 192.168.1.11 # @schema description: The host address the API Server should bind to; type: string
  apiServerPort: 6443 # @schema description: The port the API Server should bind to; type: integer; minimum: 1; maximum: 65535

# Control plane configuration
controlPlane: # @schema description: Control plane configuration; type: object
  useSystemHostname: true # @schema description: Use system hostname for kubernetes node name; type: boolean

# Worker configuration
worker: # @schema description: Worker node configuration; type: object
  useSystemHostname: true # @schema description: Use system hostname for kubernetes node name; type: boolean

# K0s parameters
k0s: # @schema description: K0s parameters; type: object
  version: v1.33.4+k0s.0 # @schema description: K0s version; type: string
  args: # @schema description: Arguments to pass to k0s controller; type: array; items: {type: string}
    - --enable-worker
    - --no-taints
    - --enable-dynamic-config
    - --disable-components=konnectivity-server
  clusterConfig: # @schema description: Cluster configuration metadata; type: object
    name: k0s # @schema description: K0s cluster config name; type: string
    namespace: kube-system # @schema description: K0s cluster config namespace; type: string
  api: # @schema description: Kubernetes API server parameters; type: object
    extraArgs: # @schema description: Map of key-values (strings) for any extra arguments to pass down to Kubernetes api-server process; type: object; additionalProperties: string
      anonymous-auth: "true" # @schema description: Enable anonymous authentication; type: string
      kubelet-preferred-address-types: "ExternalIP,InternalDNS,ExternalDNS" # @schema description: List of the preferred NodeAddressTypes to use for kubelet connections; type: string
  network: # @schema description: Network configuration for K0s; type: object
    dualStack: # @schema description: Dual stack configuration; type: object
      enabled: false # @schema description: Enable dual stack networking; type: boolean
    controlPlaneLoadBalancing: # @schema description: Control plane load balancing configuration; type: object
      enabled: false # @schema description: Enable control plane load balancing; type: boolean
    calico: # @schema description: Calico network provider configuration; type: object
      mode: vxlan # @schema description: Calico backend mode; type: string; enum: [vxlan, ipip, bird]
      ipAutodetectionMethod: can-reach=8.8.8.8 # @schema description: Method for detecting node IP address; type: string
      envVars: # @schema description: Environment variables for Calico; type: object; additionalProperties: string
        FELIX_IGNORELOOSERPF: "true" # @schema description: Ignore loose RPF check failures; type: string
        FELIX_ALLOWVXLANPACKETSFROMWORKLOADS: "true" # @schema description: Allow VXLAN packets from workloads; type: string

# Remote machine pools configuration
# See https://docs.k0smotron.io/stable/resource-reference/infrastructure.cluster.x-k8s.io-v1beta1/#pooledremotemachinespec
remoteMachines: # @schema description: Remote machine pools configuration; type: object
  controlPlane: [] # @schema description: Control plane machines (array of {name: string, ...RemoteMachineSpec fields}); type: array
  worker: [] # @schema description: Worker machines (array of {name: string, ...RemoteMachineSpec fields}); type: array
